# Extracts ONLY the NO.01 modes block from index-H.html, at mobile 390, with all three
# accordions in their OPEN state. Same mechanical transform as build.ps1 - nothing is
# hand-authored, the CSS and markup are the original.
#
# Run from the V8 folder:  powershell -File figma-export\build-modes.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot          # ...\V8
$src  = Join-Path $root 'index-H.html'
$W    = 390
$u    = [math]::Round($W / 2545, 6)

$t = [IO.File]::ReadAllText($src)

# --- 1. pin the fluid unit ---------------------------------------------------
$t = $t.Replace('--u: calc(100vw / 2545);', "--u: ${u}px; /* pinned from calc(100vw/2545) at ${W}px */")

# --- 2. mobile breakpoint: unwrap max-900, drop min-901 ----------------------
while ($true) {
  $i = $t.IndexOf('@media (max-width:900px){')
  if ($i -lt 0) { break }
  $j = $i + '@media (max-width:900px){'.Length
  $depth = 1; $k = $j
  while ($k -lt $t.Length -and $depth -gt 0) {
    if ($t[$k] -eq '{') { $depth++ } elseif ($t[$k] -eq '}') { $depth-- }
    $k++
  }
  $inner = $t.Substring($j, $k - $j - 1)
  $t = $t.Substring(0, $i) + $inner + $t.Substring($k)
}
while ($true) {
  $i = $t.IndexOf('@media (min-width:901px){')
  if ($i -lt 0) { break }
  $j = $i + '@media (min-width:901px){'.Length
  $depth = 1; $k = $j
  while ($k -lt $t.Length -and $depth -gt 0) {
    if ($t[$k] -eq '{') { $depth++ } elseif ($t[$k] -eq '}') { $depth-- }
    $k++
  }
  $t = $t.Substring(0, $i) + $t.Substring($k)
}

# --- 3. head (everything through </style>) -----------------------------------
$se = $t.IndexOf('</style>')
if ($se -lt 0) { throw '</style> not found' }
$head = $t.Substring(0, $se)
$head = [regex]::Replace($head, '(?s)<script.*?</script>', '')
$head = $head.Replace('src="Images/', 'src="../Images/').Replace('url(''Images/', 'url(''../Images/')
$head = [regex]::Replace($head, '<title>.*?</title>', "<title>NO.01 Modes - Expanded, Mobile ${W}</title>")

# --- 4. the modes block, matched by div depth --------------------------------
$ms = $t.IndexOf('<div class="modes">')
if ($ms -lt 0) { throw '<div class="modes"> not found' }
$depth = 0; $k = $ms
while ($k -lt $t.Length) {
  if ($t.Substring($k) -match '^<div\b')  { $depth++ ; $k += 4 ; continue }
  if ($t.Substring($k) -match '^</div>')  { $depth-- ; $k += 6 ; if ($depth -eq 0) { break } ; continue }
  $k++
}
$modes = $t.Substring($ms, $k - $ms)

# open every accordion, and mark the reveals done
$modes = $modes.Replace('<div class="mode rv">', '<div class="mode rv in open">')

# --- 5. export overrides -----------------------------------------------------
$override = @"

/* ===================================================================
   Extract overrides. Generated by figma-export/build-modes.ps1.
   Only the page chrome around the block is neutralised - the block's
   own type, colour and spacing are the real page at ${W}px.
   =================================================================== "/
html,body{width:${W}px!important;max-width:${W}px!important;background:var(--c-black)!important;
  margin:0!important;padding:0!important;overflow-x:visible!important}
.band.sys{padding-top:0!important;padding-bottom:0!important;margin:0!important;background:var(--c-black)!important}
.sys .row{display:block!important;margin-top:0!important;margin-bottom:0!important} /* keeps the 20px side gutter */
.sys .modes{margin:0!important}
.rv,.ri{opacity:1!important;transform:none!important;transition:none!important;animation:none!important}
*{transition:none!important;animation:none!important}
"@
$override = $override.Replace('=== "/', '=== */')

$html = $head + $override + "</style>`r`n</head>`r`n<body>`r`n" +
        "<section class=`"band sys`" id=`"system`">`r`n  <div class=`"row`">`r`n" +
        $modes + "`r`n  </div>`r`n</section>`r`n</body>`r`n</html>`r`n"

$dst = Join-Path $PSScriptRoot 'modes-expanded-mobile-390.html'
[IO.File]::WriteAllText($dst, $html, (New-Object System.Text.UTF8Encoding $false))

"{0}   {1} KB   .mode={2}  open={3}  script={4}  @media={5}" -f `
  'modes-expanded-mobile-390.html', [math]::Round($html.Length/1KB,1), `
  ([regex]::Matches($html,'class="mode ')).Count, `
  ([regex]::Matches($html,' open"')).Count, `
  ([regex]::Matches($html,'<script')).Count, `
  ([regex]::Matches($html,'@media')).Count
