# Builds the two html.to.design export files by mechanically transforming index-H.html.
# The layout, CSS and images are the ORIGINAL - only what the plugin cannot handle is changed.
#
#   1. --u is pinned to a literal px so every calc() stops depending on the import viewport
#   2. the non-target breakpoint is removed (desktop) or unwrapped so it always applies (mobile)
#   3. reveal animations are forced to their final state, so nothing imports at opacity 0
#   4. the fixed nav becomes static, so it does not float over the first section
#   5. the horizontal snap strip is unwrapped, so all four cards are visible
#   6. ::before dots and + signs get a visible fallback
#   7. <script> is removed
#   8. <video> keeps its box but shows its poster frame; <canvas> keeps its box
#
# Run from the V8 folder:  powershell -File figma-export\build.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot          # ...\V8
$src  = Join-Path $root 'index-H.html'
$out  = $PSScriptRoot

function Build([int]$W, [string]$name, [bool]$mobile) {
  $t = [IO.File]::ReadAllText($src)
  $u = [math]::Round($W / 2545, 6)

  # --- 1. pin the fluid unit -------------------------------------------------
  $t = $t.Replace('--u: calc(100vw / 2545);', "--u: ${u}px; /* pinned from calc(100vw/2545) at ${W}px */")

  # --- 2. breakpoint ---------------------------------------------------------
  if ($mobile) {
    # unwrap every max-width:900px block so its rules always apply
    while ($true) {
      $i = $t.IndexOf('@media (max-width:900px){')
      if ($i -lt 0) { break }
      $j = $i + '@media (max-width:900px){'.Length
      $depth = 1; $k = $j
      while ($k -lt $t.Length -and $depth -gt 0) {
        if ($t[$k] -eq '{') { $depth++ } elseif ($t[$k] -eq '}') { $depth-- }
        $k++
      }
      $inner = $t.Substring($j, $k - $j - 1)
      $t = $t.Substring(0, $i) + $inner + $t.Substring($k)
    }
    # drop the desktop-only block
    while ($true) {
      $i = $t.IndexOf('@media (min-width:901px){')
      if ($i -lt 0) { break }
      $j = $i + '@media (min-width:901px){'.Length
      $depth = 1; $k = $j
      while ($k -lt $t.Length -and $depth -gt 0) {
        if ($t[$k] -eq '{') { $depth++ } elseif ($t[$k] -eq '}') { $depth-- }
        $k++
      }
      $t = $t.Substring(0, $i) + $t.Substring($k)
    }
  } else {
    # desktop: delete the mobile blocks entirely so they can never fire
    while ($true) {
      $i = $t.IndexOf('@media (max-width:900px){')
      if ($i -lt 0) { break }
      $j = $i + '@media (max-width:900px){'.Length
      $depth = 1; $k = $j
      while ($k -lt $t.Length -and $depth -gt 0) {
        if ($t[$k] -eq '{') { $depth++ } elseif ($t[$k] -eq '}') { $depth-- }
        $k++
      }
      $t = $t.Substring(0, $i) + $t.Substring($k)
    }
    # single-line variant
    $t = [regex]::Replace($t, '@media \(max-width:900px\)\{[^{}]*\{[^{}]*\}[^{}]*\}', '')
    # unwrap min-width:901px so the desktop-only rules always apply
    while ($true) {
      $i = $t.IndexOf('@media (min-width:901px){')
      if ($i -lt 0) { break }
      $j = $i + '@media (min-width:901px){'.Length
      $depth = 1; $k = $j
      while ($k -lt $t.Length -and $depth -gt 0) {
        if ($t[$k] -eq '{') { $depth++ } elseif ($t[$k] -eq '}') { $depth-- }
        $k++
      }
      $inner = $t.Substring($j, $k - $j - 1)
      $t = $t.Substring(0, $i) + $inner + $t.Substring($k)
    }
  }

  # --- 3. strip scripts ------------------------------------------------------
  $t = [regex]::Replace($t, '(?s)<script.*?</script>', '')

  # --- 4. fix relative asset paths (file now lives one level deeper) ---------
  $t = $t.Replace('src="Images/', 'src="../Images/')
  $t = $t.Replace('poster="Images/', 'poster="../Images/')
  $t = $t.Replace("url('Images/", "url('../Images/")
  $t = $t.Replace('url("Images/', 'url("../Images/')
  $t = $t.Replace('src="grid-overlay.js"', 'src="../grid-overlay.js"')
  $t = $t.Replace('src="appstore-badge.png"', 'src="../appstore-badge.png"')
  $t = $t.Replace('src="Logo.svg"', 'src="../Logo.svg"')

  # --- 5. the export override block, appended so it wins -------------------
  $strip = if ($mobile) {
@'
  /* the snap strip becomes a plain row so all four cards import */
  .loop3 .lstrip{display:flex!important;overflow:visible!important;width:auto!important;
                 scroll-snap-type:none!important}
  .loop3 .lstrip .step{flex:0 0 245px!important}
'@
  } else { '' }

  $override = @"

/* ===================================================================
   html.to.design export overrides. Appended, so these win.
   Generated by figma-export/build.ps1 for a ${W}px frame.
   Nothing above this line was edited except the pinned --u and the
   breakpoint unwrapping, so the layout is the real page.
   =================================================================== */
html,body{width:${W}px!important;max-width:${W}px!important;overflow-x:visible!important}

/* reveal off: the plugin does not scroll, so anything still at opacity 0 imports invisible */
.rv,.ri{opacity:1!important;transform:none!important;transition:none!important;animation:none!important}
*{transition:none!important;animation:none!important}

/* the fixed nav would float over section one */
.nav{position:static!important}
.menuov{display:none!important}

/* pseudo-element marks have no equivalent in Figma, so give them a real box */
.loop3 .lstrip .step::before,.clog .ci::before{content:''!important;display:block!important;
  position:absolute!important;top:-3px!important;left:0!important;width:5px!important;height:5px!important;
  border-radius:50%!important;background:#A7A7A7!important}
.sys .mode h3::after,.suit5 h3::after,.acct3 .a h3::after{content:'+'!important;position:absolute!important;
  right:0!important;top:0!important;font-family:'IBM Plex Mono',monospace!important;color:#A7A7A7!important}

/* video keeps its box and shows frame one instead of importing blank */
video{background:#0A0A0A!important}
${strip}
"@

  $t = $t.Replace('</style>', $override + "`r`n</style>")

  # --- 6. mark every reveal as done in the markup too -----------------------
  $t = $t.Replace(' class="rv', ' class="rv in')
  $t = $t.Replace(' class="ri', ' class="ri in')

  # --- 6b. mobile videos: the real page swaps src to the data-m encode in JS, and the
  #         scripts are gone, so do the swap statically. The paths are regular. -----
  if ($mobile) {
    $t = [regex]::Replace($t, 'video desktop/([a-z0-9\-]+)-d\.mp4', 'video mobile/$1-m.mp4')
  }

  # --- 7. title ------------------------------------------------------------
  $t = [regex]::Replace($t, '<title>.*?</title>', "<title>II Home - $(if($mobile){'Mobile'}else{'Desktop'}) ${W} (figma export)</title>")

  $dst = Join-Path $out $name
  [IO.File]::WriteAllText($dst, $t, (New-Object System.Text.UTF8Encoding $false))

  $left = ([regex]::Matches($t,'@media \(max-width:900px\)')).Count
  $rightC = ([regex]::Matches($t,'@media \(min-width:901px\)')).Count
  "{0,-28} {1,7} KB   남은 @media: max900={2} min901={3}   script={4}" -f `
    $name, [math]::Round($t.Length/1KB,1), $left, $rightC, ([regex]::Matches($t,'<script')).Count
}

Build -W 1440 -name 'home-desktop-1440.html' -mobile $false
Build -W 390  -name 'home-mobile-390.html'   -mobile $true
"done."
